spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bmb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: classpath:env.yml
