spring:
  datasource:
    url: jdbc:mariadb://bmb.c7smkkukg8nn.ap-northeast-2.rds.amazonaws.com:3306/bmb?characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    username: admin
    password: jsl2424412
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  config:
    import: classpath:env.yml
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
