name: CI/CD Workflow

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> $GITHUB_ENV

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Java 버전 설정
          distribution: 'temurin'  # Java 배포판 설정

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Grant execute permissions for deploy script
        run: chmod +x ./deploy.sh

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy
        run: ./deploy.sh
